# Generated by Django 3.1.1 on 2020-09-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0002_auto_20200904_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='tweets',
        ),
    ]
